# Generated by Django 5.2.15 on 2026-07-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "costing_nominal_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si los reportes/dashboards muestran la base de costo nominal (peso de factura).",
                    ),
                ),
                (
                    "costing_effective_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si los reportes/dashboards muestran la base de costo efectivo (peso real).",
                    ),
                ),
                (
                    "lock",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Centinela interno del singleton; siempre True. No se expone en la API.",
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "system settings",
                "verbose_name_plural": "system settings",
                "db_table": "system_settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lock", True)),
                        name="system_settings_singleton_lock",
                    )
                ],
            },
        ),
    ]
