# Generated by Django 5.2.15 on 2026-07-01 03:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0002_seed_base_units"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceList",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible de la lista.", max_length=120
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("DESCARTE", "Descarte")],
                        help_text="Naturaleza de la lista: NORMAL o DESCARTE.",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "db_table": "price_lists",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uq_price_list_name_alive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de venta en USD (>= 0).",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        help_text="Lista a la que pertenece el precio.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pricing.pricelist",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto tarifado.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "price_list_items",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("price_list", "product"), name="uq_price_list_product"
                    )
                ],
            },
        ),
    ]
