# Generated by Django 5.2.15 on 2026-06-24 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre único del perfil.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción opcional del perfil.",
                        max_length=255,
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Permisos por (módulo, acción): {módulo: [acción, ...]} del catálogo.",
                    ),
                ),
                (
                    "visible_sensitive_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Campos sensibles que el perfil puede ver ('recurso.campo').",
                    ),
                ),
                (
                    "auto_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Capacidad de auto-aprobación (estructural en F2).",
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uq_profile_name_active",
                    )
                ],
            },
        ),
    ]
