# Generated by Django 5.2.15 on 2026-06-25 19:22

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ficha",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre o razón social del tercero.", max_length=255
                    ),
                ),
                (
                    "identification_type",
                    models.CharField(
                        choices=[
                            ("CEDULA", "Cédula"),
                            ("RUC", "RUC"),
                            ("PASAPORTE", "Pasaporte"),
                        ],
                        help_text="Tipo de identificación: CEDULA, RUC o PASAPORTE.",
                        max_length=10,
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        help_text="Número de identificación validado por dígito verificador (pasaporte sin checksum).",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Correo de contacto (opcional).",
                        max_length=254,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Teléfono o WhatsApp de contacto (opcional).",
                        max_length=20,
                    ),
                ),
                (
                    "roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("CLIENTE", "Cliente"),
                                ("PROVEEDOR", "Proveedor"),
                                ("RESPONSABLE_RUTA", "Responsable de ruta"),
                                ("CHOFER", "Chofer"),
                            ],
                            max_length=20,
                        ),
                        help_text="Roles del tercero: ≥1 de CLIENTE/PROVEEDOR/RESPONSABLE_RUTA/CHOFER.",
                        size=None,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("BLOQUEADO", "Bloqueado"),
                            ("INACTIVO", "Inactivo"),
                        ],
                        db_index=True,
                        default="ACTIVO",
                        help_text="Estado de la ficha. Cambia por acciones explícitas, no por edición directa.",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Usuario del sistema vinculado a la ficha (1:1, opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ficha",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "directory_fichas",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["roles"], name="ix_ficha_roles_gin"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "INACTIVO"), _negated=True),
                        fields=("identification_number",),
                        name="uq_ficha_identification_number_not_inactive",
                    )
                ],
            },
        ),
    ]
