# Generated by Django 5.2.15 on 2026-07-01 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ficha",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Lista de precios asignada al cliente (opcional; solo fichas con rol CLIENTE).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fichas",
                to="pricing.pricelist",
            ),
        ),
    ]
