# Generated by Django 5.2.15 on 2026-07-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        help_text="Mes contable 1–12 (validado por CheckConstraint)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Abierto"), ("CLOSED", "Cerrado")],
                        default="OPEN",
                        help_text="OPEN permite escrituras; CLOSED las bloquea.",
                        max_length=6,
                    ),
                ),
            ],
            options={
                "verbose_name": "period",
                "verbose_name_plural": "periods",
                "db_table": "period",
                "ordering": ["-year", "-month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "month"), name="period_unique_year_month"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                        name="period_month_range",
                    ),
                ],
            },
        ),
    ]
