# Generated by Django 5.2.15 on 2026-06-24 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("authz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Perfil que gobierna la autorización del usuario (no el role).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="authz.profile",
            ),
        ),
    ]
