# Generated by Django 5.2.15 on 2026-06-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_backfill_user_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Obliga al usuario a cambiar su contraseña en el primer acceso tras un reset administrativo. Se desactiva al cambiarla con éxito.",
            ),
        ),
    ]
