# Generated by Django 5.2.15 on 2026-06-25 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditTerms",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "facet",
                    models.CharField(
                        choices=[("CLIENTE", "Cliente"), ("PROVEEDOR", "Proveedor")],
                        help_text="Faceta a la que aplican los términos: CLIENTE o PROVEEDOR.",
                        max_length=10,
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Límite de crédito (≥0).",
                        max_digits=12,
                    ),
                ),
                (
                    "term_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Plazo de crédito en días (≥0)."
                    ),
                ),
                (
                    "notice_days",
                    models.PositiveIntegerField(
                        default=2, help_text="Días de aviso previo al vencimiento (≥0)."
                    ),
                ),
                (
                    "ficha",
                    models.ForeignKey(
                        help_text="Ficha a la que aplican los términos.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_terms",
                        to="directory.ficha",
                    ),
                ),
            ],
            options={
                "db_table": "credit_terms",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ficha", "facet"), name="uq_credit_terms_ficha_facet"
                    )
                ],
            },
        ),
    ]
