# Generated by Django 5.2.15 on 2026-07-01 00:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible de la categoría.", max_length=128
                    ),
                ),
                (
                    "shelf_life_days",
                    models.PositiveIntegerField(
                        default=7, help_text="Días de caducidad desde el ingreso."
                    ),
                ),
                (
                    "intake_type",
                    models.CharField(
                        choices=[("GAVETA", "Gaveta"), ("PESO", "Peso")],
                        help_text="Cómo ingresa el producto al inventario: GAVETA o PESO.",
                        max_length=8,
                    ),
                ),
                (
                    "merma_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Mínimo del rango de merma proporcional (lb). Nullable hasta definirse.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "merma_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Máximo del rango de merma proporcional (lb). Nullable hasta definirse.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "reference_qty",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("100"),
                        help_text="Cantidad de referencia del rango de merma (lb).",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "db_table": "products_categories",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uniq_category_name_alive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la unidad (p. ej. Libras).", max_length=64
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Símbolo corto (p. ej. lb, kg).", max_length=16
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Libras equivalentes a 1 unidad (base = 1). No se aplica en F5.",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "db_table": "products_units_of_measure",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uniq_unit_name_alive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, db_index=True, default=None, null=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre visible del producto.", max_length=128
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Categoría a la que pertenece el producto.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "unit_of_measure",
                    models.ForeignKey(
                        help_text="Unidad de medida del producto.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.unitofmeasure",
                    ),
                ),
            ],
            options={
                "db_table": "products_products",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("name",),
                        name="uniq_product_name_alive",
                    )
                ],
            },
        ),
    ]
